### PR TITLE
fix Jada and Gene to check if location has already been collected

### LINKED ISSUE #88: Grass Clippings Check retriggers after reloading save if Jada's quest has not yet been advanced

### PR DESCRIPTION
**Pull request by roseasromeo**
Prevents Grass and Water checks from retriggering every time a save is loaded

resolves #88

### CODE REVIEW

File: GatorRando/questMods/GeneQuestMods.cs [hunk 1]
```diff
@@ -26,10 +26,17 @@ private static void UnlockedCheeseSandwich()
         }
         else
         {
-            GameObject lootSeq = Util.GetByPath("West (Forest)/Prep Quest/Subquests/Economist/Loot Get Sequence");
-            DialogueSequencer lootSequencer = lootSeq.GetComponent<DialogueSequencer>();
-            lootSequencer.afterSequence.RemoveListener(economistQuestQS.JustProgressState);
-            lootSequencer.afterSequence.AddListener(economistQuestQS.JustProgressState);
+            if (LocationHandling.IsLocationCollected("HALF A CHEESE SANDWICH"))
+            {
+                economistQuestQS.states[1].onProgress.AddListener(economistQuestQS.JustProgressState); // If Sandwich collected, skip the get water sequence
```
Comment (roseasromeo) [inline GatorRando/questMods/GeneQuestMods.cs]:
```suggestion
                economistQuestQS.states[1].onProgress.AddListener(economistQuestQS.JustProgressState); // If Sandwich collected, skip the sandwich sequence
```
